[project]
name = "yumbox"
dynamic = ["version"] 
description = "Tools and utilities for fast prototyping of machine learning ideas!"
readme = "README.md"
requires-python = ">=3.11"
license = { file = "LICENSE" }
authors = [{ name = "Shayan", email = "shayaneshteharipour@gmail.com" }]
dependencies = [
    "numpy",
    "torch",
    "hazm>=0.9.3",
    "nltk>=3.8",
    "unicodeblock",
    "lxml",
    "parsel",
    "tqdm",
    "pillow",
    "safetensors",
    "lmdb",
    "msgpack",
    "h5py",
    "redis>=4.0.0",
]

[project.optional-dependencies]
dev = ["pytest>=7.0", "flake8>=4.0", "black>=23.0", "mypy>=0.990"]
faiss = ["faiss-cpu"]

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
include = ["yumbox"]

[project.scripts]
metrics-cli = "yumbox.scripts.cli:main"

[tool.hatch.envs.default.scripts]
test = "pytest -sv"
analyze = "python scripts/cli.py analyze {args}"
generate-docs = "python scripts/generate_docs.py"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "yumbox/_version.py"

[tool.black]
line-length = 88
target-version = ["py311"]

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--strict-markers"
testpaths = ["tests"]

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
